Feat get skills
bohuie/skillsAnalysis pull request #17
Opened 2022-03-01 01:57 UTC by OKThomas1

I still need to do proper documentation, but main features are:
Different admin styling, uses bootstrap and has a nav bar similar to the main site
A get skills page that allows admins to scrape jobs by job title and location, and then extract skills from the scraped jobs
A review skills page that allows admins to sort skills as valid, invalid, or invalid for specific job

2022-03-01 22:23 UTC, brianzhouzc requested changes

2022-03-01 22:23 UTC, brianzhouzc commented on skills_DS/skills_DS/settings.py
> +        'HOST': '127.0.0.1',
The host needs to be `postgres` for it to work in Docker. Let me know if you need help setting up the Docker enviorment.

2022-03-01 22:23 UTC, brianzhouzc commented on .gitignore
> +secrets.json
Nice

2022-03-01 22:23 UTC, brianzhouzc commented on skills_DS/api/skills_extraction.py
> +nltk.download('words')
These should be added in the docker setup script instead.

2022-03-01 22:23 UTC, brianzhouzc commented on skills_DS/api/views.py
> +				print("could not get skill")
This should return an error response.

2022-03-01 22:23 UTC, brianzhouzc commented on skills_DS/api/skills_extraction.py
> +nltk.download('words')
Don't worry about it for now - I will move them to the setup script once I merge the pdf parsing branch.

2022-03-01 22:24 UTC, brianzhouzc commented on .gitignore
> +secrets.json
We should have a `secrets_example.json` file which dummy data for reference sake.

2022-03-02 07:28 UTC, OKThomas1 commented on skills_DS/skills_DS/settings.py
> +        'HOST': '127.0.0.1',
I thought I stashed that change, but I probably added it back after I merged with develop. Next time I'll be sure to double check that I don't push that change.

2022-03-03 07:18 UTC, SanaBob approved these changes

2022-03-07 07:58 UTC, brianzhouzc approved these changes

2022-03-07 08:00 UTC, merged