readme update
bohuie/skillsAnalysis pull request #23
Opened 2022-03-09 10:04 UTC by SanaBob

2022-03-13 03:56 UTC, brianzhouzc requested changes

2022-03-13 03:56 UTC, brianzhouzc commented on README.md
> +| Get matched jobs         | Get matched jobs depending on matched skills to job description | + | + |
This feature does not exist yet

2022-03-13 03:57 UTC, brianzhouzc commented on README.md
> +| Get matched jobs         | Get matched jobs depending on matched skills to job description | + | + |
`Get matched jobs`

2022-03-13 04:54 UTC, brianzhouzc approved these changes

2022-03-14 17:50 UTC, OKThomas1 approved these changes

2022-03-15 06:18 UTC, merged